#pragma once
#include "ShurikenHeaders.h"
#include "Core/SampleBuffer.h"

/**
 * Exports slices as instrument format packages:
 *   - MPC Drum Program (.xpm)  — plain XML
 *   - Ableton Drum Rack (.adg) — gzip-compressed XML
 *   - Bitwig Drum Machine      — folder of .wav + metadata JSON
 */
struct InstrumentExporter
{
    // ── SFZ ───────────────────────────────────────────────────────────────────
    // Plain-text format supported by virtually all samplers.
    static bool exportSfz(const SampleBuffer& data,
                          const juce::File& outputDir,
                          const juce::String& kitName)
    {
        const int total    = (int)data.slices.size();
        const int padWidth = (total >= 100) ? 3 : (total >= 10) ? 2 : 1;

        juce::String sfz;
        sfz << "// " << kitName << " — generated by Bo-Shuriken\n";
        sfz << "// One region per slice, mapped to its MIDI note\n\n";

        for (int i = 0; i < total; ++i)
        {
            const auto& sl = data.slices[(size_t)i];
            const juce::String wavName = kitName + "_"
                + juce::String(i+1).paddedLeft('0', padWidth) + ".wav";

            sfz << "<region>\n";
            sfz << "  sample=Samples/" << wavName << "\n";
            sfz << "  lokey=" << sl.midiNote << " hikey=" << sl.midiNote
                << " pitch_keycenter=" << sl.midiNote << "\n";
            sfz << "  lovel=0 hivel=127\n";
            sfz << "  volume=" << juce::String(juce::Decibels::gainToDecibels((double)sl.gain), 2) << "\n";
            if (std::abs(sl.pitchSemitones) > 0.001f || std::abs(sl.pitchCents) > 0.001f)
                sfz << "  tune=" << juce::String((int)(sl.pitchSemitones * 100 + sl.pitchCents)) << "\n";
            if (sl.reversed)
                sfz << "  direction=reverse\n";
            if (sl.gainRampIn > 0.0f)
                sfz << "  ampeg_attack=" << juce::String(sl.gainRampIn, 4) << "\n";
            if (sl.gainRampOut > 0.0f)
                sfz << "  ampeg_release=" << juce::String(sl.gainRampOut, 4) << "\n";
            sfz << "\n";
        }

        juce::File sfzFile = outputDir.getChildFile(kitName + ".sfz");
        juce::FileOutputStream out(sfzFile);
        if (!out.openedOk()) return false;
        out.writeText(sfz, false, false, "\n");
        return true;
    }
    static bool exportXpm(const SampleBuffer& data,
                          const juce::File& outputDir,
                          const juce::String& kitName)
    {
        // Each slice maps to a pad. MPC pads start at MIDI note 36.
        // We export the WAV files into Samples/ and reference them.
        juce::File samplesDir = outputDir.getChildFile("Samples");
        samplesDir.createDirectory();

        // Build XML
        juce::XmlElement root("DrumProgram");
        root.setAttribute("version", "2.1");
        root.setAttribute("name", kitName);
        root.setAttribute("programType", "DrumProgram");

        auto* pads = root.createNewChildElement("Pads");

        for (int i = 0; i < (int)data.slices.size(); ++i)
        {
            const auto& sl = data.slices[(size_t)i];
            const juce::String wavName = kitName + "_" + juce::String(i+1).paddedLeft('0',3) + ".wav";

            auto* pad = pads->createNewChildElement("Pad");
            pad->setAttribute("number", i);
            pad->setAttribute("midiNote", sl.midiNote);

            auto* inst = pad->createNewChildElement("Instrument");
            auto* layer = inst->createNewChildElement("Layer");
            layer->setAttribute("number", 0);
            layer->createNewChildElement("SampleFile")
                ->setAttribute("path", "Samples/" + wavName);
            layer->createNewChildElement("VolumeRatio")->setAttribute("value", juce::String(sl.gain, 3));
            layer->createNewChildElement("PitchSemitones")->setAttribute("value", juce::String((int)sl.pitchSemitones));
            layer->createNewChildElement("PitchCents")->setAttribute("value", juce::String((int)sl.pitchCents));
            layer->createNewChildElement("Reverse")->setAttribute("value", sl.reversed ? "true" : "false");
            layer->createNewChildElement("VeloStart")->setAttribute("value", "0");
            layer->createNewChildElement("VeloEnd")->setAttribute("value", "127");
        }

        // Write the XPM file
        juce::File xpmFile = outputDir.getChildFile(kitName + ".xpm");
        if (!root.writeTo(xpmFile)) return false;

        return true;
    }

    // ── Ableton Drum Rack (.adg) ───────────────────────────────────────────────
    // ADG = gzip-compressed XML with Ableton's DrumGroupDevice schema
    static bool exportAdg(const SampleBuffer& data,
                          const juce::File& outputDir,
                          const juce::String& kitName)
    {
        // Build the XML as a string (Ableton's schema)
        juce::String xml;
        xml << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
        xml << "<Ableton MajorVersion=\"5\" MinorVersion=\"10.0.2\" SchemaChangeCount=\"3\" Creator=\"Bo-Shuriken\" Revision=\"\">\n";
        xml << "\t<DrumGroupDevice Id=\"1\">\n";
        xml << "\t\t<LomId Value=\"0\" />\n";
        xml << "\t\t<LomIdView Value=\"0\" />\n";
        xml << "\t\t<IsExpanded Value=\"true\" />\n";
        xml << "\t\t<On><Manual Value=\"true\" /></On>\n";
        xml << "\t\t<DrumBranches>\n";

        for (int i = 0; i < (int)data.slices.size(); ++i)
        {
            const auto& sl = data.slices[(size_t)i];
            const juce::String wavName = kitName + "_" + juce::String(i+1).paddedLeft('0',3) + ".wav";
            const juce::String absPath = outputDir.getChildFile("Samples").getChildFile(wavName).getFullPathName();

            xml << "\t\t\t<DrumBranchPreset Id=\"" << i << "\">\n";
            xml << "\t\t\t\t<Name Value=\"" << sl.name << "\" />\n";
            xml << "\t\t\t\t<ZoneSettings>\n";
            xml << "\t\t\t\t\t<ReceivingNote Value=\"" << sl.midiNote << "\" />\n";
            xml << "\t\t\t\t\t<SendingNote Value=\"" << sl.midiNote << "\" />\n";
            xml << "\t\t\t\t\t<ChokeGroup Value=\"0\" />\n";
            xml << "\t\t\t\t</ZoneSettings>\n";
            xml << "\t\t\t\t<DeviceChain>\n";
            xml << "\t\t\t\t\t<Devices>\n";
            xml << "\t\t\t\t\t\t<OriginalSimpler Id=\"" << i << "\">\n";
            xml << "\t\t\t\t\t\t\t<On><Manual Value=\"true\" /></On>\n";
            xml << "\t\t\t\t\t\t\t<Player>\n";
            xml << "\t\t\t\t\t\t\t\t<MultiSampleMap>\n";
            xml << "\t\t\t\t\t\t\t\t\t<SampleParts>\n";
            xml << "\t\t\t\t\t\t\t\t\t\t<MultiSamplePart Id=\"0\">\n";
            xml << "\t\t\t\t\t\t\t\t\t\t\t<Name Value=\"" << sl.name << "\" />\n";
            xml << "\t\t\t\t\t\t\t\t\t\t\t<SampleRef>\n";
            xml << "\t\t\t\t\t\t\t\t\t\t\t\t<FileRef>\n";
            xml << "\t\t\t\t\t\t\t\t\t\t\t\t\t<Path Value=\"" << absPath << "\" />\n";
            xml << "\t\t\t\t\t\t\t\t\t\t\t\t</FileRef>\n";
            xml << "\t\t\t\t\t\t\t\t\t\t\t</SampleRef>\n";
            xml << "\t\t\t\t\t\t\t\t\t\t\t<RootKey Value=\"" << sl.midiNote << "\" />\n";
            xml << "\t\t\t\t\t\t\t\t\t\t\t<Detune Value=\"" << (int)(sl.pitchSemitones * 100 + sl.pitchCents) << "\" />\n";
            xml << "\t\t\t\t\t\t\t\t\t\t\t<Volume Value=\"" << juce::String(sl.gain, 3) << "\" />\n";
            xml << "\t\t\t\t\t\t\t\t\t\t</MultiSamplePart>\n";
            xml << "\t\t\t\t\t\t\t\t\t</SampleParts>\n";
            xml << "\t\t\t\t\t\t\t\t</MultiSampleMap>\n";
            xml << "\t\t\t\t\t\t\t</Player>\n";
            xml << "\t\t\t\t\t\t</OriginalSimpler>\n";
            xml << "\t\t\t\t\t</Devices>\n";
            xml << "\t\t\t\t</DeviceChain>\n";
            xml << "\t\t\t</DrumBranchPreset>\n";
        }

        xml << "\t\t</DrumBranches>\n";
        xml << "\t</DrumGroupDevice>\n";
        xml << "</Ableton>\n";

        // Gzip-compress and write as .adg
        juce::File adgFile = outputDir.getChildFile(kitName + ".adg");
        juce::MemoryBlock xmlBytes;
        xmlBytes.append(xml.toUTF8(), (size_t)xml.getNumBytesAsUTF8());

        juce::MemoryOutputStream compressed;
        {
            juce::GZIPCompressorOutputStream gzip(&compressed, 6, false);
            gzip.write(xmlBytes.getData(), xmlBytes.getSize());
        }

        juce::FileOutputStream out(adgFile);
        if (!out.openedOk()) return false;
        out.write(compressed.getData(), compressed.getDataSize());
        return true;
    }

    // ── Bitwig Multisample (.multisample) ─────────────────────────────────────
    // Official open format: ZIP file containing multisample.xml + WAV files.
    // Spec: https://github.com/bitwig/multisample
    static bool exportBwpreset(const SampleBuffer& data,
                               const juce::File& outputDir,
                               const juce::String& kitName)
    {
        const int total    = (int)data.slices.size();
        const int padWidth = (total >= 100) ? 3 : (total >= 10) ? 2 : 1;

        // ── Build multisample.xml ─────────────────────────────────────────────
        // Must match the schema exactly: gain=linear float, tune=cents float,
        // track=integer (0=no tracking), standalone="yes" declaration.
        juce::String xml;
        xml << "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n";
        xml << "<multisample name=\"" << kitName << "\">\n";
        xml << "  <generator>Bo-Shuriken</generator>\n";
        xml << "  <category>Drums</category>\n";

        for (int i = 0; i < total; ++i)
        {
            const auto& sl = data.slices[(size_t)i];
            const juce::String wavName = kitName + "_"
                + juce::String(i+1).paddedLeft('0', padWidth) + ".wav";

            // gain: linear float (1.0 = unity), NOT dB
            const float  gain  = juce::jmax(0.0f, sl.gain);
            // tune: decimal cents float (semitones * 100 + cents)
            const double tune  = (double)sl.pitchSemitones * 100.0 + (double)sl.pitchCents;
            // track: integer 0 = no pitch tracking (one-shot drum), 1 = track keyboard
            const int    track = 0;

            xml << "  <sample file=\"" << wavName << "\""
                << " gain=\"" << juce::String(gain, 3) << "\""
                << " reverse=\"" << (sl.reversed ? "true" : "false") << "\">\n";
            xml << "    <key root=\"" << sl.midiNote << "\""
                << " tune=\"" << juce::String(tune, 2) << "\""
                << " track=\"" << track << "\""
                << " low=\"" << sl.midiNote << "\""
                << " high=\"" << sl.midiNote << "\"/>\n";
            xml << "    <velocity low=\"0\" high=\"127\"/>\n";
            xml << "  </sample>\n";
        }

        xml << "</multisample>\n";

        juce::MemoryBlock xmlBytes;
        xmlBytes.append(xml.toUTF8(), (size_t)xml.getNumBytesAsUTF8());

        // ── Render WAVs into memory blocks ────────────────────────────────────
        std::vector<ZipEntry> entries;
        entries.push_back({ "multisample.xml", std::move(xmlBytes) });

        for (int i = 0; i < total; ++i)
        {
            const auto& sl = data.slices[(size_t)i];
            const juce::String wavName = kitName + "_"
                + juce::String(i+1).paddedLeft('0', padWidth) + ".wav";
            const int len = sl.endSample - sl.startSample;
            if (len <= 0) continue;

            // Heap-allocate stream — writer takes ownership and deletes it.
            auto* wavStream = new juce::MemoryOutputStream();
            wavStream->preallocate((size_t)len * (size_t)data.numChannels * 3 + 512);

            JUCE_BEGIN_IGNORE_WARNINGS_GCC_LIKE("-Wdeprecated-declarations")
            juce::WavAudioFormat fmt;
            auto* writer = fmt.createWriterFor(wavStream, data.sampleRate,
                                               (unsigned)data.numChannels, 24, {}, 0);
            JUCE_END_IGNORE_WARNINGS_GCC_LIKE

            if (!writer) { delete wavStream; continue; }

            writer->writeFromAudioSampleBuffer(data.buffer, sl.startSample, len);

            // IMPORTANT: delete writer FIRST — this flushes the WAV header
            // and calls delete on wavStream internally. We cannot access wavStream after.
            // So we need a different approach: use a separate MemoryBlock that we fill.
            // Solution: copy the MemoryOutputStream's internal buffer before deletion.
            // But wait — MemoryOutputStream does NOT flush on delete, the WAV writer
            // writes the RIFF header on construction and updates chunk sizes on close().
            // close() is called by the destructor. So we must delete first.
            //
            // To get the data safely, we copy it via a temporary MemoryOutputStream wrapper:
            juce::MemoryOutputStream* rawPtr = wavStream;  // keep pointer

            // The writer will flush+close the stream in its destructor
            // We snapshot the stream AFTER deletion by reading from a saved pointer —
            // this is safe because MemoryOutputStream keeps its buffer until destroyed,
            // and the writer only deletes the stream pointer after closing it.
            // Actually: delete writer calls ~AudioFormatWriter which calls flush(),
            // then the stream's destructor is called inside writer's destructor.
            // So the stream IS destroyed. We cannot use rawPtr after delete writer.
            //
            // CORRECT solution: finalise the writer without deleting the stream.
            // WavAudioFormat writer's destructor calls flush(). We call flush() manually
            // via delete, but we need the data first. Use a MemoryOutputStream that
            // is NOT owned by the writer by subclassing... or simpler:
            // just write to a file and read it back. No — just capture before any close.
            //
            // SIMPLEST correct fix: don't use createWriterFor with an owned stream.
            // Write WAV manually to a MemoryBlock we control entirely.
            delete writer;   // this deletes wavStream too — its internal buffer is gone

            // Since we cannot get the data after deletion, we need to use a different
            // approach entirely. See writeWavToMemory() below.
            (void)rawPtr;
            continue;
        }

        // Use the correct approach for all slices:
        entries.resize(1);  // keep only the XML, rebuild WAVs properly
        for (int i = 0; i < total; ++i)
        {
            const auto& sl = data.slices[(size_t)i];
            const juce::String wavName = kitName + "_"
                + juce::String(i+1).paddedLeft('0', padWidth) + ".wav";
            const int len = sl.endSample - sl.startSample;
            if (len <= 0) continue;

            juce::MemoryBlock wavBytes = writeWavToMemory(data.buffer, sl.startSample,
                                                          len, data.numChannels,
                                                          data.sampleRate);
            if (wavBytes.getSize() > 0)
                entries.push_back({ wavName, std::move(wavBytes) });
        }

        // ── Pack into ZIP ─────────────────────────────────────────────────────
        juce::MemoryOutputStream zipOut;
        writeZipStored(zipOut, entries);

        juce::File outFile = outputDir.getChildFile(kitName + ".multisample");
        juce::FileOutputStream fileOut(outFile);
        if (!fileOut.openedOk()) return false;
        fileOut.write(zipOut.getData(), zipOut.getDataSize());
        return true;
    }

private:
    /** Write a WAV file into a MemoryBlock without ownership issues.
     *  Writes a minimal RIFF/WAV header manually so we fully control the buffer. */
    static juce::MemoryBlock writeWavToMemory(const juce::AudioBuffer<float>& buf,
                                              int startSample, int numSamples,
                                              int numChannels, double sampleRate)
    {
        const int    bitsPerSample = 24;
        const int    bytesPerSample = bitsPerSample / 8;
        const int    dataSize = numSamples * numChannels * bytesPerSample;
        const int    byteRate = (int)sampleRate * numChannels * bytesPerSample;
        const int    blockAlign = numChannels * bytesPerSample;

        juce::MemoryOutputStream out;
        out.preallocate((size_t)dataSize + 48);

        // RIFF header
        out.write("RIFF", 4);
        out.writeInt(36 + dataSize);          // file size - 8
        out.write("WAVE", 4);

        // fmt chunk
        out.write("fmt ", 4);
        out.writeInt(16);                     // chunk size
        out.writeShort(1);                    // PCM
        out.writeShort((short)numChannels);
        out.writeInt((int)sampleRate);
        out.writeInt(byteRate);
        out.writeShort((short)blockAlign);
        out.writeShort((short)bitsPerSample);

        // data chunk
        out.write("data", 4);
        out.writeInt(dataSize);

        // Interleaved 24-bit samples
        for (int s = 0; s < numSamples; ++s)
        {
            for (int ch = 0; ch < numChannels; ++ch)
            {
                float f = buf.getSample(ch, startSample + s);
                f = juce::jlimit(-1.0f, 1.0f, f);
                int32_t val = (int32_t)(f * 8388607.0f);  // 2^23 - 1
                // Write 3 bytes little-endian
                out.writeByte((char)( val        & 0xFF));
                out.writeByte((char)((val >>  8) & 0xFF));
                out.writeByte((char)((val >> 16) & 0xFF));
            }
        }

        return juce::MemoryBlock(out.getData(), out.getDataSize());
    }
    struct ZipEntry { juce::String name; juce::MemoryBlock data; };

    // Write a minimal ZIP archive with all entries STORED (uncompressed).
    // Bitwig's multisample spec requires STORED so samples can be streamed.
    static uint32_t crc32Block(const void* data, size_t len)
    {
        // Standard CRC-32 (ISO 3309)
        static uint32_t table[256] = {};
        static bool tableBuilt = false;
        if (!tableBuilt)
        {
            for (uint32_t i = 0; i < 256; ++i)
            {
                uint32_t c = i;
                for (int j = 0; j < 8; ++j)
                    c = (c & 1) ? (0xEDB88320u ^ (c >> 1)) : (c >> 1);
                table[i] = c;
            }
            tableBuilt = true;
        }
        uint32_t crc = 0xFFFFFFFFu;
        const uint8_t* bytes = static_cast<const uint8_t*>(data);
        for (size_t i = 0; i < len; ++i)
            crc = table[(crc ^ bytes[i]) & 0xFF] ^ (crc >> 8);
        return crc ^ 0xFFFFFFFFu;
    }

    static void writeZipStored(juce::MemoryOutputStream& out,
                                const std::vector<ZipEntry>& entries)
    {
        struct LocalHeader
        {
            uint32_t offset = 0;
            uint32_t crc    = 0;
            uint32_t size   = 0;
            juce::String name;
        };
        std::vector<LocalHeader> headers;

        auto write16 = [&](uint16_t v) { out.write(&v, 2); };
        auto write32 = [&](uint32_t v) { out.write(&v, 4); };

        for (const auto& e : entries)
        {
            LocalHeader h;
            h.offset = (uint32_t)out.getDataSize();
            h.size   = (uint32_t)e.data.getSize();
            h.name   = e.name;

            // CRC-32 of the data
            h.crc = crc32Block(e.data.getData(), e.data.getSize());

            // Local file header
            auto nameBytes = e.name.toUTF8();
            uint16_t nameLen = (uint16_t)strlen(nameBytes);

            write32(0x04034b50); // local file header signature
            write16(20);         // version needed
            write16(0);          // flags
            write16(0);          // compression method: STORED
            write16(0);          // mod time
            write16(0);          // mod date
            write32(h.crc);
            write32(h.size);
            write32(h.size);
            write16(nameLen);
            write16(0);          // extra field length
            out.write(nameBytes, nameLen);
            out.write(e.data.getData(), e.data.getSize());

            headers.push_back(h);
        }

        // Central directory
        uint32_t cdOffset = (uint32_t)out.getDataSize();
        for (const auto& h : headers)
        {
            auto nameBytes = h.name.toUTF8();
            uint16_t nameLen = (uint16_t)strlen(nameBytes);

            write32(0x02014b50); // central directory signature
            write16(20);         // version made by
            write16(20);         // version needed
            write16(0);          // flags
            write16(0);          // compression: STORED
            write16(0);          // mod time
            write16(0);          // mod date
            write32(h.crc);
            write32(h.size);
            write32(h.size);
            write16(nameLen);
            write16(0);          // extra field length
            write16(0);          // file comment length
            write16(0);          // disk number start
            write16(0);          // internal attributes
            write32(0);          // external attributes
            write32(h.offset);
            out.write(nameBytes, nameLen);
        }

        uint32_t cdSize = (uint32_t)out.getDataSize() - cdOffset;

        // End of central directory
        write32(0x06054b50);
        write16(0);  // disk number
        write16(0);  // disk with CD
        write16((uint16_t)entries.size());
        write16((uint16_t)entries.size());
        write32(cdSize);
        write32(cdOffset);
        write16(0);  // comment length
    }
};
